events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # ms-usuarios
        location /register { proxy_pass http://ms-usuarios:8000; }
        location /login { proxy_pass http://ms-usuarios:8000; }
        location /usuarios { proxy_pass http://ms-usuarios:8000; }

        # ms-pedidos
        location /orders { proxy_pass http://ms-pedidos:8000; }

        # ms-catalogo
        location /api/restaurantes { proxy_pass http://ms-catalogo:3002; }

        # ms-historial
        location /api/dashboard { proxy_pass http://ms-historial:3004; }

        # ms-consultas
        location /api/analitica { proxy_pass http://ms-consultas:3005; }
        
        # OpenAPI Specs para el Frontend Centralizado
        location /openapi/usuarios.json { proxy_pass http://ms-usuarios:8000/openapi.json; }
        location /openapi/pedidos.json { proxy_pass http://ms-pedidos:8000/openapi.json; }
        location /openapi/catalogo.json { proxy_pass http://ms-catalogo:3002/openapi.json; }
        location /openapi/historial.json { proxy_pass http://ms-historial:3004/openapi.json; }
        location /openapi/consultas.json { proxy_pass http://ms-consultas:3005/openapi.json; }
        
        # Healthchecks y otros
        location /health/catalogo { proxy_pass http://ms-catalogo:3002/health; }
        location /health/historial { proxy_pass http://ms-historial:3004/health; }
        location /health/consultas { proxy_pass http://ms-consultas:3005/health; }
        location / { proxy_pass http://ms-usuarios:8000/; }
    }
}
