version: '3.8'

services:
  ingesta-usuarios:
    build: ./ingesta-usuarios
    environment:
      - DB_HOST=${DB_IP}
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=utec
      - DB_NAME=mydb
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ~/.aws:/root/.aws:ro

  ingesta-pedidos:
    build: ./ingesta-pedidos
    environment:
      - DB_HOST=${DB_IP}
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASS=utec
      - DB_NAME=bd_api_orders
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ~/.aws:/root/.aws:ro

  ingesta-catalogo:
    build: ./ingesta-catalogo
    environment:
      - MONGO_URI=mongodb://root:utec@${DB_IP}:27017/cloudeats_catalogo?authSource=admin
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ~/.aws:/root/.aws:ro
